server:
  port: 1001
spring:
  application:
    name: register-center
eureka:
    instance:
      hostname: localhost
    client:
      fetch-registry: false
      register-with-eureka: false
    server:
      enable-self-preservation: false #关闭保护模式