server:
  port: 1003
  servlet:
    context-path: /order
spring:
  application:
    name: order-service
  kafka:
    producer:
      bootstrap-servers: 192.168.1.83:9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1001/eureka
