server:
  port: 1000
  servlet:
    context-path: /zuul

spring:
  application:
    name: zuul-proxy
#  cloud:
#    nacos:
#      discovery:
#        server-addr: http://192.168.1.83:8848
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1001/eureka

# 通过访问http://localhost:1000/zuul/actuator/routes查看简单路由信息
management:
  endpoints:
    web:
      exposure:
        include: 'routes'

zuul:
  #  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
  #  add-host-header: true #设置为true重定向是会添加host请求头
  routes:
    user-service:
      path: /userService/**
    order-service:
      path: /orderService/**

# Zuul自动集成了Ribbon和Hystrix
#hystrix:
#  command: #用于控制HystrixCommand的行为
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000 #配置HystrixCommand执行的超时时间，执行超过该时间会进行服务降级处理
#ribbon: #全局配置
#  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
#  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
