server:
  port: 1002
spring:
  application:
    name: stock-service
  kafka:
    bootstrap-servers: 192.168.1.83:9092
    consumer:
      group-id: stock-group
      auto-offset-reset: earliest
      enable-auto-commit: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1001/eureka
